### ISSUE TITLE
Add examples hosted somewhere online??

### ISSUE THREAD

**Issue by Naereen** [salomonelli/best-resume-ever#20] opened 2017-09-12 07:28 UTC
Hi,
It looks nice, but without examples of PDF that users can have a look at, it feels weird.
Any possibility of adding some?

**Comment by salomonelli** [comment] 2017-09-12 08:37
Hello @Naereen 

I would close this ticket since it is sort of a duplicate of #18 and we could continue the discussion there.

**Closed by salomonelli** 2017-09-12 08:37 UTC

**Comment by Naereen** [comment] 2017-09-12 14:47
Hi @salomonelli.
OK
