### ISSUE TITLE
Can't execute "npm run dev" successfully.

### ISSUE THREAD

**Issue by saurabhlambe** [salomonelli/best-resume-ever#190] opened 2017-12-29 05:02 UTC
### Case

I'm facing an error when I run
`npm run dev`
From the "best-resume-ever" directory

## Info
- Operating System: Antergos Linux 17.11 (Arch)
- Node-Version: v9.3.0

## Reproduce
I already had node.js installed to the latest version, and cloned the repository. I just followed these steps in README.MD file:
1. Edited the data.yml in the "resume" sub directory.
2. Ran `npm run dev` from "best-resume-ever" directory

## Error
`npm run dev

> best-resume-ever@1.0.0 predev /home/saurabh/best-resume-ever
> check-node-version --node ">= 8.0.0"

> best-resume-ever@1.0.0 dev /home/saurabh/best-resume-ever
> node build/dev-server.js

/home/saurabh/best-resume-ever/node_modules/webpack-dev-middleware/node_modules/mime/Mime.js:31
        throw new Error(
        ^

Error: Attempt to change mapping for "wasm" extension from "application/wasm" to "application/wasm". Pass `force=true` to allow this, otherwise remove "wasm" from the list of extensions for "application/wasm".
    at Mime.define (/home/saurabh/best-resume-ever/node_modules/webpack-dev-middleware/node_modules/mime/Mime.js:31:15)
    at Object.<anonymous> (/home/saurabh/best-resume-ever/node_modules/webpack-dev-middleware/lib/middleware.js:8:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/saurabh/best-resume-ever/node_modules/webpack-dev-middleware/index.js:5:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! best-resume-ever@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the best-resume-ever@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saurabh/.npm/_logs/2017-12-29T04_56_51_477Z-debug.log`

## Log file output
`cat /home/saurabh/.npm/_logs/2017-12-29T05_04_36_176Z-debug.log`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle best-resume-ever@1.0.0~predev: best-resume-ever@1.0.0
6 verbose lifecycle best-resume-ever@1.0.0~predev: unsafe-perm in lifecycle true
7 verbose lifecycle best-resume-ever@1.0.0~predev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/saurabh/best-resume-ever/node_modules/.bin:/home/saurabh/anaconda2/bin:/home/saurabh/.config/bspwm:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/afdko/Tools/linux:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/saurabh/.eclipse/eclipse/java-oxygen/eclipse/:/home/saurabh/.pycharm-edu-2017.3/bin:/home/saurabh/bin/FDK/Tools/linux:/home/saurabh/.config/bspwm/:/home/saurabh/.config/bspwm/panel/:/home/saurabh/.gem/ruby/2.4.0/bin:/home/saurabh/Documents/ides/idea-IC-173.3942.27/bin
8 verbose lifecycle best-resume-ever@1.0.0~predev: CWD: /home/saurabh/best-resume-ever
9 silly lifecycle best-resume-ever@1.0.0~predev: Args: [ '-c', 'check-node-version --node ">= 8.0.0"' ]
10 silly lifecycle best-resume-ever@1.0.0~predev: Returned: code: 0  signal: null
11 info lifecycle best-resume-ever@1.0.0~dev: best-resume-ever@1.0.0
12 verbose lifecycle best-resume-ever@1.0.0~dev: unsafe-perm in lifecycle true
13 verbose lifecycle best-resume-ever@1.0.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/saurabh/best-resume-ever/node_modules/.bin:/home/saurabh/anaconda2/bin:/home/saurabh/.config/bspwm:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/afdko/Tools/linux:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/saurabh/.eclipse/eclipse/java-oxygen/eclipse/:/home/saurabh/.pycharm-edu-2017.3/bin:/home/saurabh/bin/FDK/Tools/linux:/home/saurabh/.config/bspwm/:/home/saurabh/.config/bspwm/panel/:/home/saurabh/.gem/ruby/2.4.0/bin:/home/saurabh/Documents/ides/idea-IC-173.3942.27/bin
14 verbose lifecycle best-resume-ever@1.0.0~dev: CWD: /home/saurabh/best-resume-ever
15 silly lifecycle best-resume-ever@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
16 silly lifecycle best-resume-ever@1.0.0~dev: Returned: code: 1  signal: null
17 info lifecycle best-resume-ever@1.0.0~dev: Failed to exec dev script
18 verbose stack Error: best-resume-ever@1.0.0 dev: `node build/dev-server.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
18 verbose stack     at EventEmitter.emit (events.js:159:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:159:13)
18 verbose stack     at maybeClose (internal/child_process.js:943:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
19 verbose pkgid best-resume-ever@1.0.0
20 verbose cwd /home/saurabh/best-resume-ever
21 verbose Linux 4.14.8-1-ARCH
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
23 verbose node v9.3.0
24 verbose npm  v5.6.0
25 error code ELIFECYCLE
26 error errno 1
27 error best-resume-ever@1.0.0 dev: `node build/dev-server.js`
27 error Exit status 1
28 error Failed at the best-resume-ever@1.0.0 dev script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by GabrielCoelho** [comment] 2017-12-29 11:48
Same in #131 - try to update like #188

**Comment by pubkey** [comment] 2017-12-30 19:03
Closed. Duplicate of [#188](https://github.com/salomonelli/best-resume-ever/issues/188)

**Closed by pubkey** 2017-12-30 19:03 UTC
