### ISSUE TITLE
browser back button is broken.

### ISSUE THREAD

**Issue by songjiayang** [salomonelli/best-resume-ever#39] opened 2017-09-14 08:15 UTC
### Case
- BUG

## Info
-  Chorme: Version 60.0.3112.113 (Official Build) (64-bit)
- System: Mac Os

## Reproduce
1. Visit [home page](https://salomonelli.github.io/best-resume-ever/#/)
2. Choose 'material-dark' template.
3. Click browser back button, it  not back to home page.

**Comment by pubkey** [comment] 2017-09-14 12:24
Could reproduce.

**Comment by pubkey** [comment] 2017-09-14 12:32
Same on firefox.

**Comment by kivS** [comment] 2017-09-17 19:36
The bug also blocks the links on the page.
The problem seems to be with the chromeShadowFixer -->  src/pages/resume.vue

**Comment by salomonelli** [comment] 2017-09-18 18:56
This should be fixed now. @kivS thanks for the hint, I will take a closer look at the chromeShadowFixer

**Closed by salomonelli** 2017-09-18 18:56 UTC
Labels: bug

**Comment by songjiayang** [comment] 2017-09-20 06:24
cool, fixed, thank guys.
