### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

### ISSUE THREAD

**Issue by dadaa1** [salomonelli/best-resume-ever#78] opened 2017-09-29 09:47 UTC
![error](https://user-images.githubusercontent.com/12947361/31010616-06e48324-a53e-11e7-9a77-1b19cdfdbf10.PNG)

my system is ubuntu.
node version is  v8.4.0

**Comment by dechinkey** [comment] 2017-10-02 14:19
i have the same problem.maybe its because our node version is too high?

**Comment by mbndr** [comment] 2017-10-02 23:35
Recommended node version is 8.5. Try it with a newer version.

**Comment by salomonelli** [comment] 2017-10-20 13:54
I have fixed some issues. Please check if it works now. When does this error occur? `npm run dev` or `npm run export`?

**Comment by hasahmed** [comment] 2017-10-22 06:21
I have the same Issue running on Bash on Ubuntu on Windows using Node 8.6.0, npm 5.3.0, yarn 1.2.1, and I just pulled the repo today.

**Comment by salomonelli** [comment] 2017-10-22 10:27
I am closing this now, since I can not reproduce the error. I am using Ubuntu, node version 8.7.0, npm version 5.4.2 and no yarn. If somebody finds the solution, a PR is welcome. Otherwise further information might help to reproduce.

**Closed by salomonelli** 2017-10-22 10:27 UTC
Labels: bug
